"""Initial migration: User, Course, Attendee

Revision ID: 84a67e956c69
Revises: 
Create Date: 2026-07-19 11:27:00.198756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a67e956c69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('certificate_template_key', sa.String(length=50), nullable=True),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('course_number', sa.String(length=50), nullable=False),
    sa.Column('course_type', sa.String(length=20), nullable=False),
    sa.Column('sponsored_by', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('course_category', sa.String(length=120), nullable=False),
    sa.Column('signer_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'course_number', name='uq_courses_state_course_number')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_user_id'), ['user_id'], unique=False)

    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('student_name', sa.String(length=120), nullable=False),
    sa.Column('student_license_number', sa.String(length=50), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_name', 'student_license_number', 'completion_date', name='uq_attendees_course_student_completion')
    )
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendees_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendees_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendees_public_id'))
        batch_op.drop_index(batch_op.f('ix_attendees_course_id'))

    op.drop_table('attendees')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_user_id'))

    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
